<<<<<<< Updated upstream
name: Test LakeSuperior When makeWaves.m Changes

on: [push]
=======
name: validation-against-fortran-UMWM
# checks if PlanetWaves has been changed and if it 
# has then run model validation against known 
# results in UMWM-fortran in Earth conditions

on: [push]
    branches: [ "main" ] # runs on push to main branch
>>>>>>> Stashed changes

jobs:
  test-makeWaves:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
<<<<<<< Updated upstream
      uses: actions/checkout@v3

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
=======
      uses: actions/checkout@v4

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
>>>>>>> Stashed changes

    - name: Check if makeWaves.m changed
      id: check_diff
      run: |
<<<<<<< Updated upstream
        changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'makeWaves\.m' || true)
=======
        changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'makeWaves\.m' || true) # change to any change in planetwaves folder
>>>>>>> Stashed changes
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Run test if makeWaves.m changed
      if: steps.check_diff.outputs.changed == 'true'
<<<<<<< Updated upstream
      uses: matlab-actions/run-command@v1
=======
      uses: matlab-actions/run-command@v2
>>>>>>> Stashed changes
      with:
        command: test_LakeSuperior
